FROM hyeonjaegil/ros:melodic-desktop-full
ARG DEBIAN_FRONTEND=noninteractive
ENV core 8

RUN apt update
RUN apt install ros-melodic-image-geometry ros-melodic-pcl-ros ros-melodic-cv-bridge

RUN apt install -y --no-install-recommends apt-utils
RUN apt install -y \
      cmake build-essential unzip pkg-config autoconf \
      libboost-all-dev \
      libjpeg-dev libpng-dev libtiff-dev \
# Use libvtk5-dev, libgtk2.0-dev in ubuntu 16.04 \
      libvtk6-dev libgtk-3-dev \
      libatlas-base-dev gfortran \
      libparmetis-dev \
      python-wstool python-catkin-tools 

RUN apt install -y libtbb-dev

#ROS workspace
WORKDIR /root/catkin_ws
RUN catkin init
RUN catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DGTSAM_TANGENT_PREINTEGRATION=OFF
RUN catkin config --merge-devel
WORKDIR /root/catkin_ws/src
RUN git clone git@github.com:MIT-SPARK/Kimera-VIO-ROS.git
RUN wstool init
RUN wstool merge Kimera-VIO-ROS/install/kimera_vio_ros_ssh.rosinstall
RUN wstool update
RUN . /opt/ros/melodic/setup.sh && \
    catkin build
RUN rm -rf /var/lib/apt/lists/*
RUN echo source /opt/ros/melodic/setup.bash >> /root/.bashrc
RUN echo source /root/catkin_ws/devel/setup.bash >> /root/.bashrc

WORKDIR /root

# nvidia-container-runtime
# ENV NVIDIA_VISIBLE_DEVICES \
#     ${NVIDIA_VISIBLE_DEVICES:-all}
# ENV NVIDIA_DRIVER_CAPABILITIES \
#     ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

