name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository

    - name: Build and push Docker images
      run: | 
        for dir in $(find ./LiDAR-SLAM -mindepth 1 -maxdepth 1 -type d); do
          dir=${dir##*/}
          echo "Building image: $dir"
          docker build . --file ./LiDAR-SLAM/$dir/Dockerfile --tag hyeonjaegil/$dir:latest
        done
